package graficas;

import Logic.Mapa;
import java.awt.Color;
import java.awt.Graphics;

public class GraficaCircular extends javax.swing.JFrame {
    
    public void pintar(Mapa map, Graphics g, int mapa[][]){
        for (int x = 0; x < map.getSizeX(); x++) {
            for (int y = 0; y < map.getSizeY(); y++) {
                switch (mapa[x][y]) {
                    case 0 ->
                        g.setColor(new Color(35, 75, 249));
                    case 1 ->
                        g.setColor(new Color(0, 150, 201));
                    case 2 ->
                        g.setColor(new Color(0, 200, 143));
                    case 3 ->
                        g.setColor(new Color(255, 209, 0));
                    case 4 ->
                        g.setColor(new Color(255, 162, 0));
                    case 5 ->
                        g.setColor(new Color(169, 120, 20));
                    case 6 ->
                        g.setColor(new Color(169, 84, 8));
                    default ->
                        g.setColor(Color.red);        
                }
                g.fillRect(x * 10 + 20, y * 10 + 80, 10, 10);
                if (radioBioma.isSelected()) {
                    int biome[][] = map.generarBiomas();
                    switch (biome[x][y]) {
                        case 3 ->
                            g.setColor(new Color(0, 120, 0, 150));
                        case 2 ->
                            g.setColor(new Color(50, 150, 50, 150));
                        case 1 -> g.setColor(new Color(250, 250, 250, 150));
                    }
                }
                if (radioRadiacion.isSelected()){
                    int radiacion[][] = map.radiation();
                        switch (radiacion[x][y]) {
                        case 0 ->
                            g.setColor(new Color(35, 75, 249, 160));
                        case 1 ->
                            g.setColor(new Color(0, 150, 201, 160));
                        case 2 ->
                            g.setColor(new Color(0, 200, 143, 160));
                        case 3 ->
                            g.setColor(new Color(255, 209, 0, 160));
                        case 4 ->
                            g.setColor(new Color(255, 162, 0, 160));
                        case 5 ->
                            g.setColor(new Color(169, 120, 20, 160));
                        case 6 ->
                            g.setColor(new Color(169, 84, 8, 160));
                        default ->
                            g.setColor(Color.red);
                        }
                }
                g.fillRect(x * 10 + 20, y * 10 + 80, 10, 10);
                g.setColor(new Color(120, 120, 120));
                g.drawRect(x * 10 + 20, y * 10 + 80, 10, 10);
                
            }
        }
    }
    
    public GraficaCircular() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    boolean banderaGen = false;
    boolean banderaBiomas = false;
    boolean banderaRadiacion = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spi_1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spi_2 = new javax.swing.JSpinner();
        radialContinentes = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        radioBioma = new javax.swing.JRadioButton();
        butMostrar = new javax.swing.JButton();
        radioRadiacion = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(51, 51, 51));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Mapa");
        Background.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 800, -1, -1));

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));

        jLabel2.setText("Montes:");

        spi_1.setValue(7);

        jLabel3.setText("Altura:");

        spi_2.setValue(5);

        radialContinentes.setText("Continentes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radialContinentes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spi_2)
                            .addComponent(spi_1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spi_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spi_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radialContinentes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 810, 181, 110));

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));

        radioBioma.setText("Biomas");

        butMostrar.setText("Mostrar");
        butMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMostrarActionPerformed(evt);
            }
        });

        radioRadiacion.setText("Radiacion");
        radioRadiacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRadiacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBioma)
                    .addComponent(butMostrar)
                    .addComponent(radioRadiacion))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBioma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(radioRadiacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butMostrar)
                .addContainerGap())
        );

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 810, -1, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        banderaGen = true;
        isCreated = false;
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMostrarActionPerformed
        repaint();
        banderaBiomas = true;
    }//GEN-LAST:event_butMostrarActionPerformed

    private void radioRadiacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRadiacionActionPerformed
        repaint();
        banderaRadiacion = true;
    }//GEN-LAST:event_radioRadiacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GraficaCircular grafico = new GraficaCircular();
                grafico.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton butMostrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radialContinentes;
    private javax.swing.JRadioButton radioBioma;
    private javax.swing.JRadioButton radioRadiacion;
    private javax.swing.JSpinner spi_1;
    private javax.swing.JSpinner spi_2;
    // End of variables declaration//GEN-END:variables

    boolean isCreated = false;
    Mapa map = new Mapa(124,70);
    int mapa[][] = new int[500][500];
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        
        if(banderaGen == true){
            
            if (isCreated == false){
                map = new Mapa(124,70);
                map.setQuantityMounts((int)(spi_1.getValue()));
                map.setHeightMounts((int)(spi_2.getValue()));
                map.setIsContinent(radialContinentes.isSelected());
                int mapa[][] = map.generateMounts();
                isCreated = true;
                pintar(map, g, mapa);
            }   
        }
        
        if ((banderaBiomas || banderaRadiacion) && isCreated){
                int mapa[][] = map.getMap();
                pintar(map, g, mapa);
            }
    }
}
